### ISSUE TITLE
Not compatible with Python 3.10 (loop parameter for async.Queue has been removed)

### ISSUE THREAD

**Issue by andrey99429** [nats-io/stan.py#54]
When running code from basic usage example the following error occurs:
..\..\venv\lib\site-packages\nats\aio\client.py:310: in connect
    self._flush_queue = asyncio.Queue(

self = <[AttributeError("'Queue' object has no attribute '_maxsize'") raised in repr()] Queue object at 0x1ff1f032b60>

    def __init__(self, *, loop=_marker):
        if loop is not _marker:
>           raise TypeError(
                f'As of 3.10, the *loop* parameter was removed from '
                f'{type(self).__name__}() since it is no longer necessary'
            )
E           TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

The error occurs on the following code line:
await nc.connect(io_loop=loop)

**Comment by redoc23** [comment]
This is due to the fact that the transfer of the event loop to the Queue class from the async io package has been removed since python 3.10.
This is evidenced by the documentation:
https://docs.python.org/3.9/library/asyncio-queue.html#asyncio.PriorityQueue

Just try to remove the passing of the 'loop' parameter in the **nats** and **stan** library classes that are used in this **nats-streaming** library.

**Comment by andrey99429** [comment]
@redoc23 
Unfortunately, this doesn't fix the error.
1. After removing parameter loop=self._loop from self._flush_queue = asyncio.Queue the new error occurs:

..\..\venv\lib\site-packages\nats\aio\client.py:319: in connect
    await self._select_next_server()

async def _select_next_server(self):
               await asyncio.sleep(
                    self.options["reconnect_time_wait"], loop=self._loop
                )
               TypeError: sleep() got an unexpected keyword argument 'loop'


2. After removing parameter loop=self._loop from asyncio.sleep the following error occurs:

..\..\venv\lib\site-packages\nats\aio\client.py:319: in connect
    await self._select_next_server()

while True:
            if len(self._server_pool) == 0:
                self._current_server = None
               raise ErrNoServers
               nats.aio.errors.ErrNoServers: nats: No servers available for connection

But the server is available.

**Comment by shubb30** [comment]
Unfortunately, simply removing references to the `loop` is not possible.  The `self._loop` is what is used to create the task to ping the server, which would probably break the functionality if it were removed.

Is there any plan to update this library to work with Python 3.10?

```
210                self._ping_server_task = self._loop.create_task(
211                    self._ping_server())
```

**Comment by AdolfoVillalobos** [comment]
Hello to everyone. I understand this issue of compatibility is still present. I would be happy to contribute with a PR that helps bridging this gap, since I myself use stan in my system.

Anyone knows if the owners of the repo are still around, in order to hopefully review such a PR?

**Comment by wallyqs** [comment]
@AdolfoVillalobos I can try to take a look if you send the PR
